# This is a basic workflow to help you get started with Actions

name: Deploy String boot

# Controls when the action will run. 
on:
  push:
    branches:
      - ㅡmain

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf deploy
            mkdir deploy
            sudo sh deploy.sh
            
      - name: SCP Action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "backend/target/backend-0.0.1-SNAPSHOT.jar"
          target: "deploy"
          
      - name: SSH Action Server Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl start web-service.service
            
      - name: Send Deploy success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 서버 배포가 완료하였습니다.
